// SPDX-License-Identifier: CERN-OHL-P-2.0
// Copyright (c) 2026 XingShu Project Contributors

`timescale 1ns/1ps
// 仅用于 OOC 时序/联合仿真的可综合连接夹具，不是新增生产顶层。
// 把 FIFO -> exec 上下文 -> scheduler 和 exec_done -> response 的跨模块路径纳入计时。
module npu_v13_command_executor_timing_top #(
    parameter DIM_W=16, ADDR_W=32, BANK_W=1, OP_CFG_W=32, TAG_W=8, FIFO_DEPTH=512
)(
    input wire  clk,
    input wire  resetn,
    input wire  cmd_valid_i,
    output wire  cmd_ready_o,
    input wire [1:0] cmd_opcode_i,
    input wire [DIM_W-1:0] cmd_m_i,
    input wire [DIM_W-1:0] cmd_n_i,
    input wire [DIM_W-1:0] cmd_k_i,
    input wire [1:0] cmd_cluster_mode_i,
    input wire [2:0] cmd_layout_i,
    input wire [ADDR_W-1:0] cmd_a_base_i,
    input wire [ADDR_W-1:0] cmd_b_base_i,
    input wire [ADDR_W-1:0] cmd_c_base_i,
    input wire [BANK_W-1:0] cmd_a_bank_i,
    input wire [BANK_W-1:0] cmd_b_bank_i,
    input wire [BANK_W-1:0] cmd_c_bank_i,
    input wire [OP_CFG_W-1:0] cmd_op_cfg_i,
    input wire [TAG_W-1:0] cmd_tag_i,
    output wire  cmd_rsp_valid_o,
    input wire  cmd_rsp_ready_i,
    output wire [TAG_W-1:0] cmd_rsp_tag_o,
    output wire [2:0] cmd_rsp_status_o,
    output wire  cluster_cfg_valid_o,
    output wire [1:0] cluster_cfg_mode_o,
    input wire  cluster_cfg_ready_i,
    input wire  cluster_cfg_error_i,
    input wire [1:0] cluster_active_mode_i,
    output wire  queue_empty_o,
    output wire  queue_full_o,
    output wire [$clog2(FIFO_DEPTH+1)-1:0] queue_level_o,
    output wire  dispatcher_busy_o,
    output wire  ctx_valid_o,
    output wire [1:0] ctx_opcode_o,
    output wire [DIM_W-1:0] ctx_m_o,
    output wire [DIM_W-1:0] ctx_n_o,
    output wire [DIM_W-1:0] ctx_k_o,
    output wire [1:0] ctx_cluster_mode_o,
    output wire [2:0] ctx_layout_o,
    output wire [ADDR_W-1:0] ctx_a_base_o,
    output wire [ADDR_W-1:0] ctx_b_base_o,
    output wire [ADDR_W-1:0] ctx_c_base_o,
    output wire [BANK_W-1:0] ctx_a_bank_o,
    output wire [BANK_W-1:0] ctx_b_bank_o,
    output wire [BANK_W-1:0] ctx_c_bank_o,
    output wire [OP_CFG_W-1:0] ctx_op_cfg_o,
    output wire [TAG_W-1:0] ctx_tag_o,
    output wire  buffer_acquire_valid_o,
    input wire  buffer_acquire_ready_i,
    input wire  buffer_acquire_error_i,
    output wire  buffer_release_valid_o,
    input wire  buffer_release_ready_i,
    output wire  buffer_release_error_o,
    output wire  buffers_owned_o,
    output wire  backend_prepare_valid_o,
    input wire  backend_prepare_ready_i,
    input wire  backend_prepare_error_i,
    output wire  job_start_o,
    output wire  job_cancel_o,
    output wire  tile_batch_valid_o,
    input wire  tile_batch_ready_i,
    output wire [DIM_W-1:0] tile_batch_m_o,
    output wire [DIM_W-1:0] tile_batch_n_o,
    output wire [DIM_W-1:0] tile_batch_k_o,
    output wire [DIM_W-1:0] tile_batch_m_base_o,
    output wire [DIM_W-1:0] tile_batch_n_base_o,
    output wire [1:0] tile_batch_cluster_mode_o,
    output wire [2:0] tile_batch_layout_o,
    output wire  tile_batch_cmd_first_o,
    output wire  tile_batch_cmd_last_o,
    output wire [TAG_W-1:0] tile_batch_tag_o,
    output wire  schedule_finished_o,
    input wire  job_complete_valid_i,
    output wire  job_complete_ready_o,
    input wire [TAG_W-1:0] job_complete_tag_i,
    input wire  job_complete_error_i,
    output wire  executor_busy_o
);
    wire  exec_cmd_valid_i;
    wire  exec_cmd_ready_o;
    wire [1:0] exec_cmd_opcode_i;
    wire [DIM_W-1:0] exec_cmd_m_i;
    wire [DIM_W-1:0] exec_cmd_n_i;
    wire [DIM_W-1:0] exec_cmd_k_i;
    wire [1:0] exec_cmd_cluster_mode_i;
    wire [2:0] exec_cmd_layout_i;
    wire [ADDR_W-1:0] exec_cmd_a_base_i;
    wire [ADDR_W-1:0] exec_cmd_b_base_i;
    wire [ADDR_W-1:0] exec_cmd_c_base_i;
    wire [BANK_W-1:0] exec_cmd_a_bank_i;
    wire [BANK_W-1:0] exec_cmd_b_bank_i;
    wire [BANK_W-1:0] exec_cmd_c_bank_i;
    wire [OP_CFG_W-1:0] exec_cmd_op_cfg_i;
    wire [TAG_W-1:0] exec_cmd_tag_i;
    wire  exec_done_valid_o;
    wire  exec_done_ready_i;
    wire [TAG_W-1:0] exec_done_tag_o;
    wire  exec_done_error_o;
    wire dispatcher_exec_active_w;
    npu_v13_command_queue_dispatcher #(.DIM_W(DIM_W),.ADDR_W(ADDR_W),.BANK_W(BANK_W),
        .OP_CFG_W(OP_CFG_W),.TAG_W(TAG_W),.FIFO_DEPTH(FIFO_DEPTH)) u_dispatcher (
        .clk(clk),
        .resetn(resetn),
        .cmd_valid_i(cmd_valid_i),
        .cmd_ready_o(cmd_ready_o),
        .cmd_opcode_i(cmd_opcode_i),
        .cmd_m_i(cmd_m_i),
        .cmd_n_i(cmd_n_i),
        .cmd_k_i(cmd_k_i),
        .cmd_cluster_mode_i(cmd_cluster_mode_i),
        .cmd_layout_i(cmd_layout_i),
        .cmd_a_base_i(cmd_a_base_i),
        .cmd_b_base_i(cmd_b_base_i),
        .cmd_c_base_i(cmd_c_base_i),
        .cmd_a_bank_i(cmd_a_bank_i),
        .cmd_b_bank_i(cmd_b_bank_i),
        .cmd_c_bank_i(cmd_c_bank_i),
        .cmd_op_cfg_i(cmd_op_cfg_i),
        .cmd_tag_i(cmd_tag_i),
        .cmd_rsp_valid_o(cmd_rsp_valid_o),
        .cmd_rsp_ready_i(cmd_rsp_ready_i),
        .cmd_rsp_tag_o(cmd_rsp_tag_o),
        .cmd_rsp_status_o(cmd_rsp_status_o),
        .exec_cmd_valid_o(exec_cmd_valid_i),
        .exec_cmd_ready_i(exec_cmd_ready_o),
        .exec_cmd_opcode_o(exec_cmd_opcode_i),
        .exec_cmd_m_o(exec_cmd_m_i),
        .exec_cmd_n_o(exec_cmd_n_i),
        .exec_cmd_k_o(exec_cmd_k_i),
        .exec_cmd_cluster_mode_o(exec_cmd_cluster_mode_i),
        .exec_cmd_layout_o(exec_cmd_layout_i),
        .exec_cmd_a_base_o(exec_cmd_a_base_i),
        .exec_cmd_b_base_o(exec_cmd_b_base_i),
        .exec_cmd_c_base_o(exec_cmd_c_base_i),
        .exec_cmd_a_bank_o(exec_cmd_a_bank_i),
        .exec_cmd_b_bank_o(exec_cmd_b_bank_i),
        .exec_cmd_c_bank_o(exec_cmd_c_bank_i),
        .exec_cmd_op_cfg_o(exec_cmd_op_cfg_i),
        .exec_cmd_tag_o(exec_cmd_tag_i),
        .exec_done_valid_i(exec_done_valid_o),
        .exec_done_ready_o(exec_done_ready_i),
        .exec_done_tag_i(exec_done_tag_o),
        .exec_done_error_i(exec_done_error_o),
        .cluster_cfg_valid_o(cluster_cfg_valid_o),
        .cluster_cfg_mode_o(cluster_cfg_mode_o),
        .cluster_cfg_ready_i(cluster_cfg_ready_i),
        .cluster_cfg_error_i(cluster_cfg_error_i),
        .cluster_active_mode_i(cluster_active_mode_i),
        .queue_empty_o(queue_empty_o),
        .queue_full_o(queue_full_o),
        .queue_level_o(queue_level_o),
        .dispatcher_busy_o(dispatcher_busy_o),
        .exec_active_o(dispatcher_exec_active_w)
    );
    npu_v13_job_executor #(.DIM_W(DIM_W),.ADDR_W(ADDR_W),.BANK_W(BANK_W),
        .OP_CFG_W(OP_CFG_W),.TAG_W(TAG_W)) u_executor (
        .clk(clk),
        .resetn(resetn),
        .exec_cmd_valid_i(exec_cmd_valid_i),
        .exec_cmd_ready_o(exec_cmd_ready_o),
        .exec_cmd_opcode_i(exec_cmd_opcode_i),
        .exec_cmd_m_i(exec_cmd_m_i),
        .exec_cmd_n_i(exec_cmd_n_i),
        .exec_cmd_k_i(exec_cmd_k_i),
        .exec_cmd_cluster_mode_i(exec_cmd_cluster_mode_i),
        .exec_cmd_layout_i(exec_cmd_layout_i),
        .exec_cmd_a_base_i(exec_cmd_a_base_i),
        .exec_cmd_b_base_i(exec_cmd_b_base_i),
        .exec_cmd_c_base_i(exec_cmd_c_base_i),
        .exec_cmd_a_bank_i(exec_cmd_a_bank_i),
        .exec_cmd_b_bank_i(exec_cmd_b_bank_i),
        .exec_cmd_c_bank_i(exec_cmd_c_bank_i),
        .exec_cmd_op_cfg_i(exec_cmd_op_cfg_i),
        .exec_cmd_tag_i(exec_cmd_tag_i),
        .exec_done_valid_o(exec_done_valid_o),
        .exec_done_ready_i(exec_done_ready_i),
        .exec_done_tag_o(exec_done_tag_o),
        .exec_done_error_o(exec_done_error_o),
        .ctx_valid_o(ctx_valid_o),
        .ctx_opcode_o(ctx_opcode_o),
        .ctx_m_o(ctx_m_o),
        .ctx_n_o(ctx_n_o),
        .ctx_k_o(ctx_k_o),
        .ctx_cluster_mode_o(ctx_cluster_mode_o),
        .ctx_layout_o(ctx_layout_o),
        .ctx_a_base_o(ctx_a_base_o),
        .ctx_b_base_o(ctx_b_base_o),
        .ctx_c_base_o(ctx_c_base_o),
        .ctx_a_bank_o(ctx_a_bank_o),
        .ctx_b_bank_o(ctx_b_bank_o),
        .ctx_c_bank_o(ctx_c_bank_o),
        .ctx_op_cfg_o(ctx_op_cfg_o),
        .ctx_tag_o(ctx_tag_o),
        .buffer_acquire_valid_o(buffer_acquire_valid_o),
        .buffer_acquire_ready_i(buffer_acquire_ready_i),
        .buffer_acquire_error_i(buffer_acquire_error_i),
        .buffer_release_valid_o(buffer_release_valid_o),
        .buffer_release_ready_i(buffer_release_ready_i),
        .buffer_release_error_o(buffer_release_error_o),
        .buffers_owned_o(buffers_owned_o),
        .backend_prepare_valid_o(backend_prepare_valid_o),
        .backend_prepare_ready_i(backend_prepare_ready_i),
        .backend_prepare_error_i(backend_prepare_error_i),
        .job_start_o(job_start_o),
        .job_cancel_o(job_cancel_o),
        .tile_batch_valid_o(tile_batch_valid_o),
        .tile_batch_ready_i(tile_batch_ready_i),
        .tile_batch_m_o(tile_batch_m_o),
        .tile_batch_n_o(tile_batch_n_o),
        .tile_batch_k_o(tile_batch_k_o),
        .tile_batch_m_base_o(tile_batch_m_base_o),
        .tile_batch_n_base_o(tile_batch_n_base_o),
        .tile_batch_cluster_mode_o(tile_batch_cluster_mode_o),
        .tile_batch_layout_o(tile_batch_layout_o),
        .tile_batch_cmd_first_o(tile_batch_cmd_first_o),
        .tile_batch_cmd_last_o(tile_batch_cmd_last_o),
        .tile_batch_tag_o(tile_batch_tag_o),
        .schedule_finished_o(schedule_finished_o),
        .job_complete_valid_i(job_complete_valid_i),
        .job_complete_ready_o(job_complete_ready_o),
        .job_complete_tag_i(job_complete_tag_i),
        .job_complete_error_i(job_complete_error_i),
        .busy_o(executor_busy_o)
    );
endmodule

